stages:
  data_ingestion:
    cmd: python3 src/MLOPSCNNCLASSIFIER/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MLOPSCNNCLASSIFIER/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/KIDNEY_CT_SCAN
  
  prepare_base_model:
    cmd: python3 src/MLOPSCNNCLASSIFIER/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/MLOPSCNNCLASSIFIER/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE

    outs:
      - artifacts/prepare_base_model
  
  training:
    cmd: python3 src/MLOPSCNNCLASSIFIER/pipeline/stage_03_model_training.py
    deps:
      - src/MLOPSCNNCLASSIFIER/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/KIDNEY_CT_SCAN
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
  
  evaluation:
    cmd: python3 src/MLOPSCNNCLASSIFIER/pipeline/stage_04_model_evaluation.py
    deps:
      - src/MLOPSCNNCLASSIFIER/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/training/model.h5
      - artifacts/data_ingestion/KIDNEY_CT_SCAN
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    
    metrics:
      - scores.json:
          cache: false